In [1]:
#Difference between copy and view

In [2]:
import numpy as np

#changes made to the old array will not affect the new array or vice versa if copy function is used

X=np.array([1,2,3,4])
Y=X.copy()
X[1]=6
print(X)
print(Y)

[1 6 3 4]
[1 2 3 4]


In [3]:
#changes made to the old array will reflect in new array or vice versa if view function is used

X=np.array([1,2,3,4])
Y=X.view()
X[1]=6
print(X)
print(Y)

[1 6 3 4]
[1 6 3 4]
